<a href="https://colab.research.google.com/github/ary11793/rep-1/blob/main/FP_vertices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
# Importing libraries
import numpy as np
import struct

def float_to_ieee_754_16bit(num):
    # Convert the float number to 16-bit half-precision float using NumPy
    np_half_float = np.float16(num)
    #print(np_half_float)

    # Pack the 16-bit half-precision float as binary data (2 bytes)
    packed = struct.pack('e', np_half_float)
    #print(packed)

    # Unpack it as a 16-bit unsigned integer
    ieee_754_16bit = struct.unpack('H', packed)[0]
    #print(ieee_754_16bit)

    # Return the binary representation as a string
    binary_format = format(ieee_754_16bit, '016b')
    #Grouping the binary string as 1 bit, then 5 bits, then 10 bits
    group_1 = binary_format[:1]    # First 1 bit
    group_5 = binary_format[1:6]   # Next 5 bits
    group_10 = binary_format[6:16] # Last 10 bits

#Joining the groups with spaces in between
    return f'{group_1} {group_5} {group_10}'

def matrix_to_ieee_754_16bit(matrix):
    # Convert each element in the matrix
    ieee_matrix = np.vectorize(float_to_ieee_754_16bit)(matrix)
    return ieee_matrix

In [2]:
# Step 1: Open and read file
with open('teapot.data', 'r') as file:
    data = file.readlines()

In [3]:
# Step 2: Parse the contents and store the numbers in a list
numbers_list = []
for line in data:
    numbers = line.strip().split()
    numbers_list.extend([float(num) for num in numbers])

In [6]:
# Step 3: Converting the list to a NumPy array and reshape it into an 8x3 matrix

matrix = np.array(numbers_list).reshape(306, 3)
print(matrix)

[[ 1.40000e+00  0.00000e+00  2.40000e+00]
 [ 1.40000e+00 -7.84000e-01  2.40000e+00]
 [ 7.80000e-01 -1.40000e+00  2.40000e+00]
 [ 0.00000e+00 -1.40000e+00  2.40000e+00]
 [ 1.33750e+00  0.00000e+00  2.53125e+00]
 [ 1.33750e+00 -7.49000e-01  2.53125e+00]
 [ 7.49000e-01 -1.33750e+00  2.53125e+00]
 [ 0.00000e+00 -1.33750e+00  2.53125e+00]
 [ 1.43750e+00  0.00000e+00  2.53125e+00]
 [ 1.43750e+00 -8.05000e-01  2.53125e+00]
 [ 8.05000e-01 -1.43750e+00  2.53125e+00]
 [ 0.00000e+00 -1.43750e+00  2.53125e+00]
 [ 1.50000e+00  0.00000e+00  2.40000e+00]
 [ 1.50000e+00 -8.40000e-01  2.40000e+00]
 [ 8.40000e-01 -1.50000e+00  2.40000e+00]
 [ 0.00000e+00 -1.50000e+00  2.40000e+00]
 [-7.84000e-01 -1.40000e+00  2.40000e+00]
 [-1.40000e+00 -7.84000e-01  2.40000e+00]
 [-1.40000e+00  0.00000e+00  2.40000e+00]
 [-7.49000e-01 -1.33750e+00  2.53125e+00]
 [-1.33750e+00 -7.49000e-01  2.53125e+00]
 [-1.33750e+00  0.00000e+00  2.53125e+00]
 [-8.05000e-01 -1.43750e+00  2.53125e+00]
 [-1.43750e+00 -8.05000e-01  2.531

In [7]:
# Printing the IEEE representation matrix
ieee_754_matrix = matrix_to_ieee_754_16bit(matrix)
'''print(type(ieee_754_matrix[0][1]))
print(ieee_754_matrix[0][0]*2)'''
print(ieee_754_matrix)

[['0 01111 0110011010' '0 00000 0000000000' '0 10000 0011001101']
 ['0 01111 0110011010' '1 01110 1001000110' '0 10000 0011001101']
 ['0 01110 1000111101' '1 01111 0110011010' '0 10000 0011001101']
 ['0 00000 0000000000' '1 01111 0110011010' '0 10000 0011001101']
 ['0 01111 0101011010' '0 00000 0000000000' '0 10000 0100010000']
 ['0 01111 0101011010' '1 01110 0111111110' '0 10000 0100010000']
 ['0 01110 0111111110' '1 01111 0101011010' '0 10000 0100010000']
 ['0 00000 0000000000' '1 01111 0101011010' '0 10000 0100010000']
 ['0 01111 0111000000' '0 00000 0000000000' '0 10000 0100010000']
 ['0 01111 0111000000' '1 01110 1001110001' '0 10000 0100010000']
 ['0 01110 1001110001' '1 01111 0111000000' '0 10000 0100010000']
 ['0 00000 0000000000' '1 01111 0111000000' '0 10000 0100010000']
 ['0 01111 1000000000' '0 00000 0000000000' '0 10000 0011001101']
 ['0 01111 1000000000' '1 01110 1010111000' '0 10000 0011001101']
 ['0 01110 1010111000' '1 01111 1000000000' '0 10000 0011001101']
 ['0 00000

In [8]:
#Storing values in a .txt file
with open('matrix_input.txt', 'w') as f:
    # Write matrix A
    for row in ieee_754_matrix:
        f.write(' '.join(map(str, row)) + '\n')